Repository dfds/terraform-grafana-cloud, pull requests merged in 2024-05, with the labels that each got.

#29 Add data source dependency
  stack.tf
Labels: release:patch

#31 Add multi-stack token
  README.md
  outputs.tf
  providers.tf
  stack.tf
  variables.tf
Labels: release:minor

#32 Add grafana_data_source submodule
  README.md
  grafana_data_source/main.tf
  grafana_data_source/variables.tf
  grafana_data_source/versions.tf
  outputs.tf
Labels: release:minor

#33 Fix multi stack read only
  outputs.tf
  stack.tf
Labels: release:patch

#34 Migrate renovate config
  renovate.json
Labels: norelease

#35 Add Slack integration. Also prepare for setting up a policy once we have our own stack
  grafana_notification/main.tf
  grafana_notification/variables.tf
  grafana_notification/versions.tf
Labels: release:minor
