Repository dfds/terraform-grafana-cloud, pull requests merged in 2024-08, with the labels that each got.

#57 creating resources for service account for stack editors
  README.md
  onepassword-item.tf
  stack.tf
  variables.tf
Labels: release:major

#58 fix editor sa and 1password items
  README.md
  onepassword-item.tf
  stack.tf
  variables.tf
Labels: release:patch

#59 Allow using OpenTofu 1.8 and higher
  grafana_alert/versions.tofu
  grafana_dashboard/versions.tofu
  grafana_data_source/versions.tofu
  grafana_data_source_athena/versions.tofu
  grafana_data_source_cloudwatch/versions.tofu
  grafana_folder/versions.tofu
  grafana_notification/versions.tofu
  grafana_synthetic_check/versions.tofu
  renovate.json
Labels: release:minor

#61 toggle for collectors
  otel-collector.tf
  otel-collector/values.yaml
  providers.tf
Labels: release:patch

#62 Add module for managing Infinity data sources
  grafana_data_source_infinity/main.tf
  grafana_data_source_infinity/variables.tf
  grafana_data_source_infinity/versions.tf
  grafana_data_source_infinity/versions.tofu
Labels: release:minor

#63 fix toggle service extension on collector config
  otel-collector/values.yaml
Labels: release:patch
