Repository dfds/terraform-grafana-cloud, pull requests merged in 2024-07, with the labels that each got.

#44 data source read only token scope updated
  stack.tf
Labels: release:minor

#45 no output when write only token is disabled
  outputs.tf
Labels: release:patch

#46 wip: otel collector
  README.md
  otel-collector.tf
  otel-collector/values.yaml
  variables.tf
  versions.tf
Labels: release:minor

#47 fix: conditional otlp_auth_header_value
  otel-collector.tf
Labels: release:patch

#48 fix: prefix otel resource names via helm chart
  otel-collector.tf
Labels: release:patch

#49 write otlp to param store
  README.md
  stack.tf
Labels: release:minor

#50 collector svc name based on cname. resource label added
  otel-collector.tf
  otel-collector/values.yaml
Labels: release:patch

#51 output stack slug for dependency support
  README.md
  outputs.tf
Labels: release:patch

#52 enable setting default option on data sources
  grafana_data_source/main.tf
  grafana_data_source/variables.tf
Labels: release:minor

#53 store stack details in 1password item
  .github/CODEOWNERS
  README.md
  onepassword-item.tf
  variables.tf
  versions.tf
Labels: release:major
