Repository dfds/terraform-grafana-cloud, pull requests merged in 2024-02, with the labels that each got.

#2 Update route53 record
  README.md
  route53.tf
  variables.tf
Labels: release:minor

#3 Create modules for managing Grafana Cloud resources
  .github/CODEOWNERS
  grafana_dashboard/main.tf
  grafana_dashboard/variables.tf
  grafana_dashboard/versions.tf
  grafana_folder/main.tf
  grafana_folder/outputs.tf
  grafana_folder/variables.tf
  grafana_folder/versions.tf
Labels: release:minor

#4 Configure Renovate
  renovate.json
Labels: release:patch

#6 Update actions/checkout action to v4
  .github/workflows/documentation.yaml
  .github/workflows/secret-detection.yaml
Labels: release:minor

#8 output folder uid
  grafana_folder/outputs.tf
Labels: release:minor

#12 Change from looping over list to looping over map in order to fix TF state conflicts in new content
  grafana_dashboard/main.tf
Labels: release:minor

#11 enable creating alerts from json files in folder
  grafana_alert/main.tf
  grafana_alert/variables.tf
  grafana_alert/versions.tf
Labels: release:minor

#13 Add plugin installations support
  README.md
  stack.tf
  variables.tf
Labels: release:minor

#15 return null on missing annotations
  grafana_alert/main.tf
Labels: release:patch

#16 Add support for synthetic monitoring
  README.md
  synthetic-monitoring.tf
  variables.tf
Labels: release:minor

#17 Add ssm parameter for terraform token
  README.md
  stack.tf
Labels: release:minor

#18 Rename service account
  README.md
  stack.tf
Labels: release:minor

#19 trivy instead of tfsec
  .github/workflows/tfsec.yaml
Labels: norelease

#14 Add support for synthetic monitoring from JSON input
  grafana_synthetic_check/main.tf
  grafana_synthetic_check/variables.tf
  grafana_synthetic_check/versions.tf
Labels: release:minor

#21 CW and Athena data source installation
  grafana_data_source_athena/main.tf
  grafana_data_source_athena/outputs.tf
  grafana_data_source_athena/variables.tf
  grafana_data_source_athena/versions.tf
  grafana_data_source_cloudwatch/main.tf
  grafana_data_source_cloudwatch/outputs.tf
  grafana_data_source_cloudwatch/variables.tf
  grafana_data_source_cloudwatch/versions.tf
Labels: release:minor
